---
title: Compendium Finance (TM)
timezone: UTC
collections:
  articles:
    title: Articles
    output: true
    permalink: articles/:title.data:output_ext
  assets:
    title: Assets
    output: true
  cards:
    title: Cards
    output: false
  feeds:
    title: Feeds
    output: true
  posts:
    title: Posts
    output: true
  resources:
    title: Resources
    output: true
    permalink: resources/:title.data:output_ext
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: articles
  values:
    status: current
    layout: article-data
    section: articles
    source: external
    bg_img_darken: true
    format_class: article
- scope:
    path: ''
    type: resources
  values:
    layout: article-data
    format_class: resources
    section: resource-cards
    no_date: true
- scope:
    path: ''
    type: posts
  values:
    layout: post
email: your-email@compendiumfinance.com
description: This is the static content site for compendiumfinance.com
baseurl: 
url: http://compendiumfinance.com
twitter_username: choosesimple
github_username: jekyll
trademark: Compendium Finance&#x2122;
social: compendiumfinance
pmd_path: assets/pmd-1.0.0
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
assets:
  compress:
    css: true
    js: true
